/*
 * HardwareSerial.h
 *
 *  Created on: 24.09.2019 г.
 *      Author: ceco
 */

#ifndef SRC_MARLIN_SRC_HAL_HAL_STM32_F767XX_INCLUDE_HARDWARESERIAL_H_
#define SRC_MARLIN_SRC_HAL_HAL_STM32_F767XX_INCLUDE_HARDWARESERIAL_H_



#endif /* SRC_MARLIN_SRC_HAL_HAL_STM32_F767XX_INCLUDE_HARDWARESERIAL_H_ */
